language: ruby
rvm:
  - 1.9.3
before_script: 'git add Gemfile.lock && git commit -m "Gemfile hack"'
script: "bundle exec ruhoh publish github"
notifications:
  recipients:
    - jaimalchohan@gmail.com
branches:
  only:
    - gh-pages