baseurl     = "http://jaimalchohan.com"  # the baseurl for your website
title       = "on cooking. on running. on code"     # blog title
paginate    = 5                    # the number of posts on a page

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[author]
    # Optional. Used in RSS feed meta information.
    name = "Jaimal Chohan"
    email = "jaimalchohan@gmail.com"

[params]
    # language code for your website
    languagecode = "en-GB"

    # name of the site author; used in header meta information
    author = "jaimalchohan"

    # copyright text; used in footer
    copyright = "2015 ~ Jaimal Chohan"

    # social links, used in footer, these must be full URLs.
    twitter     = "https://twitter.com/jaimalchohan"
    github      = "https://github.com/jaimalchohan"
    #facebook    = "https://www.facebook.com/<username>"
    #delicious   = "https://delicious.com/<username>"
    linkedin    = "https://www.linkedin.com/in/jaimalchohan"
    #flickr      = "https://www.flickr.com/photos/<username>"

    # show default summaries on the frontpage or not
    use_summaries = false

# naming of the elements in your blog/site
[params.strings]
    # name of the link to the homepage
    home_navbar_link = "Jaimal Chohan"

    # name of the link to the blog page
    blog_navbar_link = "Blog"

    # name of the header used in the post list page
    posts_list_header = "Posts"

    # used date format
    date_format = '02.01.2006'

[params.theme]
    inverse = true     # indicating if the theme should use inversed colors
    name = "paper"   # name of the theme to use

    # list of possible theme names that can be used
    # name = "cerulean"
    # name = "cosmo"
    # name = "cyborg"
    # name = "default"
    # name = "flatly"
    # name = "journal"
    # name = "lumen"
    # name = "paper"
    # name = "readable"
    # name = "sandstone"
    # name = "simplex"
    # name = "slate"
    # name = "spacelabs"
    # name = "superhero"
    # name = "united"
    # name = "yeti"

[[menu.main]]
    name = "Github"
    weight = 100
    url = "https://github.com/jaimalchohan"

 [[menu.main]]
    name = "LinkedIn"
    weight = 110
    url = "http://www.linkedin.com/pub/jaimal-chohan/20/496/48b"